// <auto-generated />
namespace UCR_ManagementSystem.DatabaseContexts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class allocateClassroom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(allocateClassroom));
        
        string IMigrationMetadata.Id
        {
            get { return "201812121534263_allocateClassroom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
